//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dictionary_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dictionary_id: i32,
    pub label: String,
    pub value: String,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub tenant_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dictionaries::Entity",
        from = "Column::DictionaryId",
        to = "super::dictionaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dictionaries,
}

impl Related<super::dictionaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dictionaries.def()
    }
}
