//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod departments;
pub mod dictionaries;
pub mod dictionary_entries;
pub mod login_log;
pub mod menus;
pub mod notif;
pub mod oper_log;
pub mod page_config;
pub mod positions;
pub mod roles;
pub mod roles_menus;
pub mod scheduled_task;
pub mod scheduled_task_log;
pub mod storage_config;
pub mod sync_source;
pub mod sync_source_table;
pub mod sys_config;
pub mod tenant;
pub mod user_sessions;
pub mod users;
pub mod users_departments;
pub mod users_positions;
pub mod users_roles;
