//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "oper_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    pub business_type: i32,
    pub method: String,
    pub request_method: String,
    pub oper_url: String,
    pub oper_ip: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub oper_param: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub json_result: Option<String>,
    pub status: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub oper_time: Option<DateTimeWithTimeZone>,
    pub cost_time: i64,
    pub oper_name: String,
    pub dept_name: Option<String>,
    pub tenant_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
