//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::departments::Entity as Departments;
pub use super::dictionaries::Entity as Dictionaries;
pub use super::dictionary_entries::Entity as DictionaryEntries;
pub use super::login_log::Entity as LoginLog;
pub use super::menus::Entity as Menus;
pub use super::notif::Entity as Notif;
pub use super::oper_log::Entity as OperLog;
pub use super::page_config::Entity as PageConfig;
pub use super::positions::Entity as Positions;
pub use super::roles::Entity as Roles;
pub use super::roles_menus::Entity as RolesMenus;
pub use super::scheduled_task::Entity as ScheduledTask;
pub use super::scheduled_task_log::Entity as ScheduledTaskLog;
pub use super::storage_config::Entity as StorageConfig;
pub use super::sync_source::Entity as SyncSource;
pub use super::sync_source_table::Entity as SyncSourceTable;
pub use super::sys_config::Entity as SysConfig;
pub use super::tenant::Entity as Tenant;
pub use super::user_sessions::Entity as UserSessions;
pub use super::users::Entity as Users;
pub use super::users_departments::Entity as UsersDepartments;
pub use super::users_positions::Entity as UsersPositions;
pub use super::users_roles::Entity as UsersRoles;
