//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub cron_expr: String,
    pub handler: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub params: Option<Json>,
    pub status: String,
    pub last_run_at: Option<DateTimeWithTimeZone>,
    pub next_run_at: Option<DateTimeWithTimeZone>,
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub tenant_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::scheduled_task_log::Entity")]
    ScheduledTaskLog,
}

impl Related<super::scheduled_task_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledTaskLog.def()
    }
}
