//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_source_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub source_id: i32,
    pub source_table: String,
    pub target_table: String,
    pub target_connection_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub field_mapping: Option<Json>,
    pub sync_mode: String,
    pub status: String,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub last_row_count: Option<i32>,
    pub tenant_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sync_source::Entity",
        from = "Column::SourceId",
        to = "super::sync_source::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SyncSource,
}

impl Related<super::sync_source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncSource.def()
    }
}
