//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_source")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub source_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub connection_config: Json,
    pub target_table: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub field_mapping: Option<Json>,
    pub sync_mode: String,
    pub status: String,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub tenant_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sync_source_table::Entity")]
    SyncSourceTable,
}

impl Related<super::sync_source_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncSourceTable.def()
    }
}
